name: RubySolitaire

options:
  bundleIdPrefix: org.xord
  deploymentTarget:
    iOS: 14.0

settingGroups:
  all:
    SWIFT_OBJC_BRIDGING_HEADER: RubySolitaire/BridgingHeader.h
  app:
    ENABLE_PREVIEWS: YES
    DEVELOPMENT_ASSET_PATHS: "\"RubySolitaire/Preview Content\""
  test:
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES

settings:
  base:
    MARKETING_VERSION: 1.0.1
    CURRENT_PROJECT_VERSION: 1.0.1.7
    DEVELOPMENT_TEAM: $(TEAM_ID)
  configs:
    debug:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    majorVersion: 9.0.0
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    majorVersion: 9.0.0

targets:
  RubySolitaire:
    type: application
    platform: iOS
    dependencies:
      - framework: CoreMedia.framework
        embed: false
      - framework: JavaScriptCore.framework
        embed: false
      - package: Firebase
        product: FirebaseAnalyticsSwift
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseRemoteConfigSwift
      - package: GoogleMobileAds
        product: GoogleMobileAds
    sources:
      - RubySolitaire
      - main.rb
      - path: lib
        type: folder
      - path: data
        type: folder
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
      groups: [all, app]
    info:
      path: RubySolitaire/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleDisplayName: Solitaire
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
          #- UIInterfaceOrientationLandscapeLeft
          #- UIInterfaceOrientationLandscapeRight
        #UISupportedInterfaceOrientations~ipad:
          #- UIInterfaceOrientationPortrait
          #- UIInterfaceOrientationPortraitUpsideDown
          #- UIInterfaceOrientationLandscapeLeft
          #- UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription:
          Ruby scripts will be able to retrieve images from the camera.
        NSUserTrackingUsageDescription:
          This identifier will be used to deliver personalized ads to you.
        GADApplicationIdentifier:  ca-app-pub-3940256099942544~1458002511
        GADGameScreenBottomBanner: ca-app-pub-3940256099942544/2934735716
        GADGameScreenInterstitial: ca-app-pub-3940256099942544/4411468910
        SKAdNetworkItems:
          - SKAdNetworkIdentifier: cstr6suwn9.skadnetwork
          - SKAdNetworkIdentifier: 4fzdc2evr5.skadnetwork
          - SKAdNetworkIdentifier: 4pfyvq9l8r.skadnetwork
          - SKAdNetworkIdentifier: 2fnua5tdw4.skadnetwork
          - SKAdNetworkIdentifier: ydx93a7ass.skadnetwork
          - SKAdNetworkIdentifier: 5a6flpkh64.skadnetwork
          - SKAdNetworkIdentifier: p78axxw29g.skadnetwork
          - SKAdNetworkIdentifier: v72qych5uu.skadnetwork
          - SKAdNetworkIdentifier: ludvb6z3bs.skadnetwork
          - SKAdNetworkIdentifier: cp8zw746q7.skadnetwork
          - SKAdNetworkIdentifier: c6k4g5qg8m.skadnetwork
          - SKAdNetworkIdentifier: s39g8k73mm.skadnetwork
          - SKAdNetworkIdentifier: 3qy4746246.skadnetwork
          - SKAdNetworkIdentifier: 3sh42y64q3.skadnetwork
          - SKAdNetworkIdentifier: f38h382jlk.skadnetwork
          - SKAdNetworkIdentifier: hs6bdukanm.skadnetwork
          - SKAdNetworkIdentifier: prcb7njmu6.skadnetwork
          - SKAdNetworkIdentifier: v4nxqhlyqp.skadnetwork
          - SKAdNetworkIdentifier: wzmmz9fp6w.skadnetwork
          - SKAdNetworkIdentifier: yclnxrl5pm.skadnetwork
          - SKAdNetworkIdentifier: t38b2kh725.skadnetwork
          - SKAdNetworkIdentifier: 7ug5zh24hu.skadnetwork
          - SKAdNetworkIdentifier: 9rd848q2bz.skadnetwork
          - SKAdNetworkIdentifier: y5ghdn5j9k.skadnetwork
          - SKAdNetworkIdentifier: n6fk4nfna4.skadnetwork
          - SKAdNetworkIdentifier: v9wttpbfk9.skadnetwork
          - SKAdNetworkIdentifier: n38lu8286q.skadnetwork
          - SKAdNetworkIdentifier: 47vhws6wlr.skadnetwork
          - SKAdNetworkIdentifier: kbd757ywx3.skadnetwork
          - SKAdNetworkIdentifier: 9t245vhmpl.skadnetwork
          - SKAdNetworkIdentifier: a2p9lx4jpn.skadnetwork
          - SKAdNetworkIdentifier: 22mmun2rn5.skadnetwork
          - SKAdNetworkIdentifier: 4468km3ulz.skadnetwork
          - SKAdNetworkIdentifier: 2u9pt9hc89.skadnetwork
          - SKAdNetworkIdentifier: 8s468mfl3y.skadnetwork
          - SKAdNetworkIdentifier: av6w8kgt66.skadnetwork
          - SKAdNetworkIdentifier: klf5c3l5u5.skadnetwork
          - SKAdNetworkIdentifier: ppxm28t8ap.skadnetwork
          - SKAdNetworkIdentifier: 424m5254lk.skadnetwork
          - SKAdNetworkIdentifier: ecpz2srf59.skadnetwork
          - SKAdNetworkIdentifier: uw77j35x4d.skadnetwork
          - SKAdNetworkIdentifier: mlmmfzh3r3.skadnetwork
          - SKAdNetworkIdentifier: 578prtvx9j.skadnetwork
          - SKAdNetworkIdentifier: 4dzt52r2t5.skadnetwork
          - SKAdNetworkIdentifier: gta9lk7p23.skadnetwork
          - SKAdNetworkIdentifier: e5fvkxwrpn.skadnetwork
          - SKAdNetworkIdentifier: 8c4e2ghe7u.skadnetwork
          - SKAdNetworkIdentifier: zq492l623r.skadnetwork
          - SKAdNetworkIdentifier: 3rd42ekr43.skadnetwork
          - SKAdNetworkIdentifier: 3qcr597p9d.skadnetwork

  RubySolitaireTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: RubySolitaire
    sources:
      - RubySolitaireTests
    settings:
      groups: [all, test]
    info:
      path: RubySolitaireTests/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)

  RubySolitaireUITests:
    type: bundle.ui-testing
    platform: iOS
    dependencies:
      - target: RubySolitaire
    sources:
      - RubySolitaireUITests
    settings:
      groups: [all, test]
    info:
      path: RubySolitaireUITests/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
