# -*- mode: ruby -*-


require 'yaml'
require 'base64'


def config(key, defval = nil)
  $config ||= YAML.load_file(File.expand_path '../config.yml', __dir__) rescue {}
  key = key.to_s.upcase
  ENV[key] or $config[key] or defval or raise "missing #{key}"
end

def project()
  "#{config :app_name}.xcodeproj"
end

def workspace()
  "#{config :app_name}.xcworkspace"
end

def asc_api_key()
  $api_key ||= app_store_connect_api_key(
    key_id:      config(:asc_key_id),
    issuer_id:   config(:asc_issuer_id),
    key_content: config(:asc_key_content)&.then {|s| Base64.decode64 s})
end

def match_params()
  {
    api_key:                 asc_api_key,
    app_identifier:          config(:app_id),
    git_url:                 config(:certs_url),
    git_branch:              config(:app_name),
  }.tap {|params|
    pat = config :pat, ''
    if !pat.empty?
      puts config(:certs_username)
      params[:git_basic_authorization] =
        Base64.strict_encode64 "#{config :certs_username}:#{pat}"
    end
  }
end

def upload_params()
  {
    api_key:        asc_api_key,
    app_identifier: config(:app_id)
  }
end


default_platform(:ios)

platform :ios do
  lane :setup_code_signing do
    type     = config :match_type, 'Development'
    identity = type == 'Development' ? type : 'Distribution'
    update_code_signing_settings(
      path:                  project,
      team_id:               config(:team_id),
      code_sign_identity:    "Apple #{identity}",
      profile_name:          "match #{type} #{config :app_id}",
      use_automatic_signing: false)
  end

  lane :match_update do
    %w[development adhoc appstore].each do |type|
      sync_code_signing type: type, **match_params
    end
  end

  lane :match_fetch do
    %w[development adhoc appstore].each do |type|
      sync_code_signing type: type, **match_params, readonly: true
    end
  end

  lane :match_delete do
    %w[development distribution].each do |type|
      match_nuke type: type
    end
  end

  desc "Upload to TestFlight"
  lane :release_testflight do
    sync_code_signing type: 'appstore', **match_params, readonly: true

    build_app workspace: workspace, scheme: config(:app_name)

    upload_to_testflight changelog: config(:changelog), **upload_params
  end
end
