#!/usr/bin/ruby


def ls_files(regexp)
  `git ls-files`
    .lines(chomp: true)
    .select {|path| path =~ regexp}
end


%w[config.yml GoogleService-Info.plist].each do |name|
  raise "Do not commit #{name}" unless ls_files(/#{Regexp.escape name}/).empty?
end
