name: Push to CD

on:
  push:
    tags: ['v[0-9]*']

jobs:
  push:
    if: github.repository == 'xord/solitaire'

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: push to repository for continuous delivery
        run: |
          git checkout master
          git remote add cd https://github.com/xord/solitaire_cd
          git fetch cd --tags
          git push cd master --tags
