name: Release iOS

on:
  push:
    tags: ['v[0-9]*']

jobs:
  push-to-cd:
    if: github.repository == 'xord/solitaire'

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: check
        run: |
          git tag -n99
          git branch -v

      - name: push to repository for continuous delivery
        run: |
          git remote add cd https://github.com/xord/solitaire_cd
          git push cd master --tags

  testflight:
    if: github.repository == 'xord/solitaire_cd'

    runs-on: macos-latest

    steps:
      - name: ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: checkout
        uses: actions/checkout@v2

      - name: setup dependencies
        run: "ruby -I.github/workflows -rutils -e 'setup_dependencies'"

      - name: create config file
        run: echo '${{ secrets.CONFIG }}' | base64 -d > config.yml

      - name: upload to testflight
        run: rake release:testflight
