name: Release iOS

on:
  push:
    tags: ['v[0-9]*']

jobs:
  testflight:
    if: github.repository == 'xord/solitaire_cd'

    runs-on: macos-latest

    steps:
      - name: ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: checkout
        uses: actions/checkout@v2

      - name: setup dependencies
        run: "ruby -I.github/workflows -rutils -e 'setup_dependencies'"

      - name: create config file
        run: echo '${{ secrets.CONFIG }}' | base64 -d > config.yml

      - name: upload to testflight
        run: rake release:testflight
